{% set name = "scriptengine-tasks-ecearth" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9564a389b1f57e4987faf8734e9aaab5bdd645bc28df496c58b08f254b4f4199

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - scriptengine >=0.8.1
    - pyyaml >=5.1
    - matplotlib-base >=3.1
    - numpy >=1.18
    - imageio >=2.18
    - scitools-iris !=3.2.0,!=3.2.0.post0,>=3.1
    - cartopy >=0.20
    - python-redmine

test:
  commands:
    - pip check
    - se --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uwefladrich/scriptengine-tasks-ecearth
  summary: ScriptEngine tasks for use with the EC-Earth climate model
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - uwefladrich
    - valentinaschueller
